export const DATE_TIME_STORAGE_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSSZ';
export const DATE_STORAGE_FORMAT = 'YYYY-MM-DD';
export const MONTH_DAY_STORAGE_FORMAT = '--MM-DD';
export const DATE_EXTENDED_DISPLAY_FORMAT = 'MMM D, YYYY';
export const DATE_SHORT_DISPLAY_FORMAT = 'DD/MM/YYYY';
export const MONTH_DAY_DISPLAY_FORMAT = 'Do MMM';
