
export enum RequestTypeEnum {

    WORK_CERTIFICATE = 'WORK_CERTIFICATE',
    MISSION_CERTIFICATE = 'MISSION_CERTIFICATE',
    PAYROLL = 'PAYROLL',
    SALARY_CERTIFICATE = 'SALARY_CERTIFICATE',
    USER_GUIDE = 'USER_GUIDE',
    ETIQUETTE_TYPE = "ETIQUETTE_TYPE",
    REMINDER = "REMINDER",




}
